version: '3.8'

services:
  autanalysis_api:
    build: ./backend
    ports:
      - "8000:8000" # Manteniamo esposta la porta per il development e per il frontend_client
    environment:
      - MONGODB_URL=mongodb://autanalysis_mongodb:27017
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - autanalysis_mongodb

  autanalysis_admin_web:
    build: 
      context: ./frontend_admin
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - autanalysis_api

  autanalysis_mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
