name: frontend_admin
description: Dashboard Web Admin per Autify
publish_to: 'none'
version: 2.18.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  file_picker: ^8.0.0
  fl_chart: ^0.68.0
  shimmer: ^3.0.0
  flutter_markdown: ^0.7.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
