name: frontend_client
description: App Client per Autify (Data Entry)
publish_to: 'none'
version: 2.17.3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
